#!/usr/bin/env bash

rm -rf target

mkdir target

cd target || exit

cmake ..

make LIBRARY/float128/dpml_exception.c.i
make LIBRARY/float128/dpml_four_over_pi.c.i
make LIBRARY/float128/dpml_ux_bessel.c.i
make LIBRARY/float128/dpml_ux_bid.c.i
make LIBRARY/float128/dpml_ux_cbrt.c.i
make LIBRARY/float128/dpml_ux_erf.c.i
make LIBRARY/float128/dpml_ux_exp.c.i
make LIBRARY/float128/dpml_ux_int.c.i
make LIBRARY/float128/dpml_ux_inv_hyper.c.i
make LIBRARY/float128/dpml_ux_inv_trig.c.i
make LIBRARY/float128/dpml_ux_lgamma.c.i
make LIBRARY/float128/dpml_ux_log.c.i
make LIBRARY/float128/dpml_ux_mod.c.i
make LIBRARY/float128/dpml_ux_ops.c.i
make LIBRARY/float128/dpml_ux_ops_64.c.i
make LIBRARY/float128/dpml_ux_pow.c.i
make LIBRARY/float128/dpml_ux_powi.c.i
make LIBRARY/float128/dpml_ux_sqrt.c.i
make LIBRARY/float128/dpml_ux_trig.c.i
make LIBRARY/float128/sqrt_tab_t.c.i
make LIBRARY/src/bid128_2_str_tables.c.i
make LIBRARY/src/bid128_acos.c.i
make LIBRARY/src/bid128_acosh.c.i
make LIBRARY/src/bid128_add.c.i
make LIBRARY/src/bid128_asin.c.i
make LIBRARY/src/bid128_asinh.c.i
make LIBRARY/src/bid128_atan2.c.i
make LIBRARY/src/bid128_atan.c.i
make LIBRARY/src/bid128_atanh.c.i
make LIBRARY/src/bid128.c.i
make LIBRARY/src/bid128_cbrt.c.i
make LIBRARY/src/bid128_compare.c.i
make LIBRARY/src/bid128_cos.c.i
make LIBRARY/src/bid128_cosh.c.i
make LIBRARY/src/bid128_div.c.i
make LIBRARY/src/bid128_erf.c.i
make LIBRARY/src/bid128_erfc.c.i
make LIBRARY/src/bid128_exp10.c.i
make LIBRARY/src/bid128_exp2.c.i
make LIBRARY/src/bid128_exp.c.i
make LIBRARY/src/bid128_expm1.c.i
make LIBRARY/src/bid128_fdimd.c.i
make LIBRARY/src/bid128_fma.c.i
make LIBRARY/src/bid128_fmod.c.i
make LIBRARY/src/bid128_frexp.c.i
make LIBRARY/src/bid128_hypot.c.i
make LIBRARY/src/bid128_ldexp.c.i
make LIBRARY/src/bid128_lgamma.c.i
make LIBRARY/src/bid128_llquantexpd.c.i
make LIBRARY/src/bid128_llrintd.c.i
make LIBRARY/src/bid128_llround.c.i
make LIBRARY/src/bid128_log10.c.i
make LIBRARY/src/bid128_log1p.c.i
make LIBRARY/src/bid128_log2.c.i
make LIBRARY/src/bid128_logb.c.i
make LIBRARY/src/bid128_logbd.c.i
make LIBRARY/src/bid128_log.c.i
make LIBRARY/src/bid128_lrintd.c.i
make LIBRARY/src/bid128_lround.c.i
make LIBRARY/src/bid128_minmax.c.i
make LIBRARY/src/bid128_modf.c.i
make LIBRARY/src/bid128_mul.c.i
make LIBRARY/src/bid128_nearbyintd.c.i
make LIBRARY/src/bid128_next.c.i
make LIBRARY/src/bid128_nexttowardd.c.i
make LIBRARY/src/bid128_noncomp.c.i
make LIBRARY/src/bid128_pow.c.i
make LIBRARY/src/bid128_quantexpd.c.i
make LIBRARY/src/bid128_quantize.c.i
make LIBRARY/src/bid128_quantumd.c.i
make LIBRARY/src/bid128_rem.c.i
make LIBRARY/src/bid128_round_integral.c.i
make LIBRARY/src/bid128_scalb.c.i
make LIBRARY/src/bid128_scalbl.c.i
make LIBRARY/src/bid128_sin.c.i
make LIBRARY/src/bid128_sinh.c.i
make LIBRARY/src/bid128_sqrt.c.i
make LIBRARY/src/bid128_string.c.i
make LIBRARY/src/bid128_tan.c.i
make LIBRARY/src/bid128_tanh.c.i
make LIBRARY/src/bid128_tgamma.c.i
make LIBRARY/src/bid128_to_int16.c.i
make LIBRARY/src/bid128_to_int32.c.i
make LIBRARY/src/bid128_to_int64.c.i
make LIBRARY/src/bid128_to_int8.c.i
make LIBRARY/src/bid128_to_uint16.c.i
make LIBRARY/src/bid128_to_uint32.c.i
make LIBRARY/src/bid128_to_uint64.c.i
make LIBRARY/src/bid128_to_uint8.c.i
make LIBRARY/src/bid64_acos.c.i
make LIBRARY/src/bid64_acosh.c.i
make LIBRARY/src/bid64_add.c.i
make LIBRARY/src/bid64_asin.c.i
make LIBRARY/src/bid64_asinh.c.i
make LIBRARY/src/bid64_atan2.c.i
make LIBRARY/src/bid64_atan.c.i
make LIBRARY/src/bid64_atanh.c.i
make LIBRARY/src/bid64_cbrt.c.i
make LIBRARY/src/bid64_compare.c.i
make LIBRARY/src/bid64_cos.c.i
make LIBRARY/src/bid64_cosh.c.i
make LIBRARY/src/bid64_div.c.i
make LIBRARY/src/bid64_erf.c.i
make LIBRARY/src/bid64_erfc.c.i
make LIBRARY/src/bid64_exp10.c.i
make LIBRARY/src/bid64_exp2.c.i
make LIBRARY/src/bid64_exp.c.i
make LIBRARY/src/bid64_expm1.c.i
make LIBRARY/src/bid64_fdimd.c.i
make LIBRARY/src/bid64_fma.c.i
make LIBRARY/src/bid64_fmod.c.i
make LIBRARY/src/bid64_frexp.c.i
make LIBRARY/src/bid64_hypot.c.i
make LIBRARY/src/bid64_ldexp.c.i
make LIBRARY/src/bid64_lgamma.c.i
make LIBRARY/src/bid64_llquantexpd.c.i
make LIBRARY/src/bid64_llrintd.c.i
make LIBRARY/src/bid64_llround.c.i
make LIBRARY/src/bid64_log10.c.i
make LIBRARY/src/bid64_log1p.c.i
make LIBRARY/src/bid64_log2.c.i
make LIBRARY/src/bid64_logb.c.i
make LIBRARY/src/bid64_logbd.c.i
make LIBRARY/src/bid64_log.c.i
make LIBRARY/src/bid64_lrintd.c.i
make LIBRARY/src/bid64_lround.c.i
make LIBRARY/src/bid64_minmax.c.i
make LIBRARY/src/bid64_modf.c.i
make LIBRARY/src/bid64_mul.c.i
make LIBRARY/src/bid64_nearbyintd.c.i
make LIBRARY/src/bid64_next.c.i
make LIBRARY/src/bid64_nexttowardd.c.i
make LIBRARY/src/bid64_noncomp.c.i
make LIBRARY/src/bid64_pow.c.i
make LIBRARY/src/bid64_quantexpd.c.i
make LIBRARY/src/bid64_quantize.c.i
make LIBRARY/src/bid64_quantumd.c.i
make LIBRARY/src/bid64_rem.c.i
make LIBRARY/src/bid64_round_integral.c.i
make LIBRARY/src/bid64_scalb.c.i
make LIBRARY/src/bid64_scalbl.c.i
make LIBRARY/src/bid64_sin.c.i
make LIBRARY/src/bid64_sinh.c.i
make LIBRARY/src/bid64_sqrt.c.i
make LIBRARY/src/bid64_string.c.i
make LIBRARY/src/bid64_tan.c.i
make LIBRARY/src/bid64_tanh.c.i
make LIBRARY/src/bid64_tgamma.c.i
make LIBRARY/src/bid64_to_bid128.c.i
make LIBRARY/src/bid64_to_int16.c.i
make LIBRARY/src/bid64_to_int32.c.i
make LIBRARY/src/bid64_to_int64.c.i
make LIBRARY/src/bid64_to_int8.c.i
make LIBRARY/src/bid64_to_uint16.c.i
make LIBRARY/src/bid64_to_uint32.c.i
make LIBRARY/src/bid64_to_uint64.c.i
make LIBRARY/src/bid64_to_uint8.c.i
make LIBRARY/src/bid32_acos.c.i
make LIBRARY/src/bid32_acosh.c.i
make LIBRARY/src/bid32_add.c.i
make LIBRARY/src/bid32_asin.c.i
make LIBRARY/src/bid32_asinh.c.i
make LIBRARY/src/bid32_atan2.c.i
make LIBRARY/src/bid32_atan.c.i
make LIBRARY/src/bid32_atanh.c.i
make LIBRARY/src/bid32_cbrt.c.i
make LIBRARY/src/bid32_compare.c.i
make LIBRARY/src/bid32_cos.c.i
make LIBRARY/src/bid32_cosh.c.i
make LIBRARY/src/bid32_div.c.i
make LIBRARY/src/bid32_erf.c.i
make LIBRARY/src/bid32_erfc.c.i
make LIBRARY/src/bid32_exp10.c.i
make LIBRARY/src/bid32_exp2.c.i
make LIBRARY/src/bid32_exp.c.i
make LIBRARY/src/bid32_expm1.c.i
make LIBRARY/src/bid32_fdimd.c.i
make LIBRARY/src/bid32_fma.c.i
make LIBRARY/src/bid32_fmod.c.i
make LIBRARY/src/bid32_frexp.c.i
make LIBRARY/src/bid32_hypot.c.i
make LIBRARY/src/bid32_ldexp.c.i
make LIBRARY/src/bid32_lgamma.c.i
make LIBRARY/src/bid32_llquantexpd.c.i
make LIBRARY/src/bid32_llrintd.c.i
make LIBRARY/src/bid32_llround.c.i
make LIBRARY/src/bid32_log10.c.i
make LIBRARY/src/bid32_log1p.c.i
make LIBRARY/src/bid32_log2.c.i
make LIBRARY/src/bid32_logb.c.i
make LIBRARY/src/bid32_logbd.c.i
make LIBRARY/src/bid32_log.c.i
make LIBRARY/src/bid32_lrintd.c.i
make LIBRARY/src/bid32_lround.c.i
make LIBRARY/src/bid32_minmax.c.i
make LIBRARY/src/bid32_modf.c.i
make LIBRARY/src/bid32_mul.c.i
make LIBRARY/src/bid32_nearbyintd.c.i
make LIBRARY/src/bid32_next.c.i
make LIBRARY/src/bid32_nexttowardd.c.i
make LIBRARY/src/bid32_noncomp.c.i
make LIBRARY/src/bid32_pow.c.i
make LIBRARY/src/bid32_quantexpd.c.i
make LIBRARY/src/bid32_quantize.c.i
make LIBRARY/src/bid32_quantumd.c.i
make LIBRARY/src/bid32_rem.c.i
make LIBRARY/src/bid32_round_integral.c.i
make LIBRARY/src/bid32_scalb.c.i
make LIBRARY/src/bid32_scalbl.c.i
make LIBRARY/src/bid32_sin.c.i
make LIBRARY/src/bid32_sinh.c.i
make LIBRARY/src/bid32_sqrt.c.i
make LIBRARY/src/bid32_string.c.i
make LIBRARY/src/bid32_sub.c.i
make LIBRARY/src/bid32_tan.c.i
make LIBRARY/src/bid32_tanh.c.i
make LIBRARY/src/bid32_tgamma.c.i
make LIBRARY/src/bid32_to_bid128.c.i
make LIBRARY/src/bid32_to_bid64.c.i
make LIBRARY/src/bid32_to_int16.c.i
make LIBRARY/src/bid32_to_int32.c.i
make LIBRARY/src/bid32_to_int64.c.i
make LIBRARY/src/bid32_to_int8.c.i
make LIBRARY/src/bid32_to_uint16.c.i
make LIBRARY/src/bid32_to_uint32.c.i
make LIBRARY/src/bid32_to_uint64.c.i
make LIBRARY/src/bid32_to_uint8.c.i
make LIBRARY/src/bid_binarydecimal.c.i
make LIBRARY/src/bid_convert_data.c.i
make LIBRARY/src/bid_decimal_data.c.i
make LIBRARY/src/bid_decimal_globals.c.i
make LIBRARY/src/bid_dpd.c.i
make LIBRARY/src/bid_feclearexcept.c.i
make LIBRARY/src/bid_fegetexceptflag.c.i
make LIBRARY/src/bid_feraiseexcept.c.i
make LIBRARY/src/bid_fesetexceptflag.c.i
make LIBRARY/src/bid_fetestexcept.c.i
make LIBRARY/src/bid_flag_operations.c.i
make LIBRARY/src/bid_from_int.c.i
make LIBRARY/src/bid_round.c.i
make LIBRARY/src/strtod128.c.i
make LIBRARY/src/strtod32.c.i
make LIBRARY/src/strtod64.c.i
make LIBRARY/src/wcstod128.c.i
make LIBRARY/src/wcstod32.c.i
make LIBRARY/src/wcstod64.c.i